<?php

declare(strict_types=1);

namespace App\Modules\Persons\Database\Seeders;

use App\Modules\Persons\Models\Person;
use App\Modules\Persons\Enums\Area;
use App\Modules\Persons\Enums\ContractType;
use App\Modules\Persons\Enums\DocumentType;
use App\Modules\Persons\Enums\EducationLevel;
use App\Modules\Persons\Enums\Gender;
use App\Modules\Persons\Enums\MaritalStatus;
use App\Modules\Persons\Enums\PensionSystem;
use App\Modules\Persons\Enums\Site;
use App\Modules\Persons\Enums\WorkShift;
use Illuminate\Database\Seeder;

/**
 * Lo ejecuta automáticamente Database\Seeders\DatabaseSeeder.
 * No depende de Faker: usa datos fijos para funcionar en producción.
 */
class PersonsSeeder extends Seeder
{
    public function run(): void
    {
        if (Person::query()->exists()) {
            $this->command?->info('Módulo Personas: ya hay datos, se omite el seeder.');
            return;
        }

        $persons = [
            // Activos
            ['document_type' => DocumentType::Dni->value,        'document_number' => '45231890', 'first_name' => 'Carlos',    'last_name' => 'Ramírez Torres',      'birth_date' => '1985-03-12', 'gender' => Gender::Male->value,   'email' => 'c.ramirez@municipio.gob.pe',  'phone' => '987654321', 'address' => 'Av. Los Pinos 123, Lima',       'marital_status' => MaritalStatus::Married->value,  'education_level' => EducationLevel::University->value,   'children_count' => 2, 'emergency_contact_name' => 'María Ramírez',   'emergency_contact_phone' => '912345678', 'ruc' => null, 'pension_system' => PensionSystem::Afp->value,  'area' => Area::Administration->value,     'position' => 'Administrador',           'contract_type' => ContractType::Appointed->value,      'hire_date' => '2018-01-15', 'work_shift' => WorkShift::Morning->value,   'site' => Site::Main->value,  'is_active' => true,  'notes' => null],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '72841056', 'first_name' => 'Ana',       'last_name' => 'García López',         'birth_date' => '1990-07-22', 'gender' => Gender::Female->value, 'email' => 'a.garcia@municipio.gob.pe',   'phone' => '976543210', 'address' => 'Jr. Las Flores 456, Lima',      'marital_status' => MaritalStatus::Single->value,   'education_level' => EducationLevel::Technical->value,    'children_count' => 0, 'emergency_contact_name' => 'Luis García',     'emergency_contact_phone' => '923456789', 'ruc' => null, 'pension_system' => PensionSystem::Onp->value,  'area' => Area::Treasury->value,           'position' => 'Tesorera',                'contract_type' => ContractType::Cas->value,            'hire_date' => '2020-03-01', 'work_shift' => WorkShift::Morning->value,   'site' => Site::Main->value,  'is_active' => true,  'notes' => null],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '31456789', 'first_name' => 'Jorge',     'last_name' => 'Mendoza Quispe',       'birth_date' => '1978-11-05', 'gender' => Gender::Male->value,   'email' => 'j.mendoza@municipio.gob.pe',  'phone' => '965432109', 'address' => 'Calle Real 789, Lima',          'marital_status' => MaritalStatus::Married->value,  'education_level' => EducationLevel::University->value,   'children_count' => 3, 'emergency_contact_name' => 'Rosa Mendoza',    'emergency_contact_phone' => '934567890', 'ruc' => '10314567891', 'pension_system' => PensionSystem::Afp->value, 'area' => Area::PublicWorks->value,       'position' => 'Ingeniero Civil',          'contract_type' => ContractType::Appointed->value,      'hire_date' => '2010-06-20', 'work_shift' => WorkShift::Morning->value,   'site' => Site::Main->value,  'is_active' => true,  'notes' => null],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '58963214', 'first_name' => 'Lucía',     'last_name' => 'Vargas Huamán',        'birth_date' => '1992-04-18', 'gender' => Gender::Female->value, 'email' => 'l.vargas@municipio.gob.pe',   'phone' => '954321098', 'address' => 'Urb. Los Cedros 321, Lima',     'marital_status' => MaritalStatus::Single->value,   'education_level' => EducationLevel::University->value,   'children_count' => 1, 'emergency_contact_name' => 'Pedro Vargas',    'emergency_contact_phone' => '945678901', 'ruc' => null, 'pension_system' => PensionSystem::Afp->value,  'area' => Area::Health->value,             'position' => 'Médico',                  'contract_type' => ContractType::Cas->value,            'hire_date' => '2021-09-01', 'work_shift' => WorkShift::Rotating->value, 'site' => Site::North->value, 'is_active' => true,  'notes' => null],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '47852369', 'first_name' => 'Miguel',    'last_name' => 'Quispe Ccallo',        'birth_date' => '1983-09-30', 'gender' => Gender::Male->value,   'email' => 'm.quispe@municipio.gob.pe',   'phone' => '943210987', 'address' => 'Av. Progreso 654, Lima',        'marital_status' => MaritalStatus::Married->value,  'education_level' => EducationLevel::Technical->value,    'children_count' => 2, 'emergency_contact_name' => 'Carmen Quispe',   'emergency_contact_phone' => '956789012', 'ruc' => null, 'pension_system' => PensionSystem::Onp->value,  'area' => Area::Transportation->value,    'position' => 'Conductor',               'contract_type' => ContractType::Hired->value,          'hire_date' => '2015-02-10', 'work_shift' => WorkShift::Afternoon->value, 'site' => Site::South->value, 'is_active' => true,  'notes' => null],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '63214587', 'first_name' => 'Patricia',  'last_name' => 'Huanca Mamani',        'birth_date' => '1988-12-25', 'gender' => Gender::Female->value, 'email' => 'p.huanca@municipio.gob.pe',   'phone' => '932109876', 'address' => 'Jr. Unión 987, Lima',           'marital_status' => MaritalStatus::Divorced->value, 'education_level' => EducationLevel::Postgraduate->value, 'children_count' => 0, 'emergency_contact_name' => 'Julio Huanca',    'emergency_contact_phone' => '967890123', 'ruc' => '10632145871', 'pension_system' => PensionSystem::Afp->value, 'area' => Area::EducationCulture->value,  'position' => 'Docente',                 'contract_type' => ContractType::Appointed->value,      'hire_date' => '2012-04-05', 'work_shift' => WorkShift::Morning->value,   'site' => Site::East->value,  'is_active' => true,  'notes' => null],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '89456321', 'first_name' => 'Roberto',   'last_name' => 'Flores Condori',       'birth_date' => '1975-06-14', 'gender' => Gender::Male->value,   'email' => 'r.flores@municipio.gob.pe',   'phone' => '921098765', 'address' => 'Urb. El Bosque 147, Lima',      'marital_status' => MaritalStatus::Married->value,  'education_level' => EducationLevel::Secondary->value,    'children_count' => 4, 'emergency_contact_name' => 'Gloria Flores',   'emergency_contact_phone' => '978901234', 'ruc' => null, 'pension_system' => PensionSystem::Onp->value,  'area' => Area::PublicCleaning->value,    'position' => 'Operario de Limpieza',    'contract_type' => ContractType::Hired->value,          'hire_date' => '2008-11-01', 'work_shift' => WorkShift::Morning->value,   'site' => Site::Main->value,  'is_active' => true,  'notes' => null],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '52147896', 'first_name' => 'Sandra',    'last_name' => 'Chávez Apaza',         'birth_date' => '1995-02-08', 'gender' => Gender::Female->value, 'email' => 's.chavez@municipio.gob.pe',   'phone' => '910987654', 'address' => 'Av. Industrial 258, Lima',      'marital_status' => MaritalStatus::Single->value,   'education_level' => EducationLevel::University->value,   'children_count' => 0, 'emergency_contact_name' => 'Marco Chávez',    'emergency_contact_phone' => '989012345', 'ruc' => null, 'pension_system' => PensionSystem::Afp->value,  'area' => Area::CitizenSecurity->value,   'position' => 'Serenazgo',               'contract_type' => ContractType::ServiceContract->value, 'hire_date' => '2022-01-10', 'work_shift' => WorkShift::Night->value,     'site' => Site::West->value,  'is_active' => true,  'notes' => null],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '74563289', 'first_name' => 'Eduardo',   'last_name' => 'Mamani Ticona',        'birth_date' => '1981-08-17', 'gender' => Gender::Male->value,   'email' => 'e.mamani@municipio.gob.pe',   'phone' => '999876543', 'address' => 'Jr. Comercio 369, Lima',        'marital_status' => MaritalStatus::Married->value,  'education_level' => EducationLevel::Technical->value,    'children_count' => 2, 'emergency_contact_name' => 'Silvia Mamani',   'emergency_contact_phone' => '990123456', 'ruc' => null, 'pension_system' => PensionSystem::Onp->value,  'area' => Area::Environment->value,       'position' => 'Inspector Ambiental',     'contract_type' => ContractType::Cas->value,            'hire_date' => '2019-07-15', 'work_shift' => WorkShift::Morning->value,   'site' => Site::Annex->value, 'is_active' => true,  'notes' => null],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '36987521', 'first_name' => 'Carmen',    'last_name' => 'Puma Ccana',           'birth_date' => '1987-05-29', 'gender' => Gender::Female->value, 'email' => 'c.puma@municipio.gob.pe',     'phone' => '988765432', 'address' => 'Urb. Santa Rosa 741, Lima',     'marital_status' => MaritalStatus::Married->value,  'education_level' => EducationLevel::University->value,   'children_count' => 1, 'emergency_contact_name' => 'Ángel Puma',      'emergency_contact_phone' => '901234567', 'ruc' => '10369875211', 'pension_system' => PensionSystem::Afp->value, 'area' => Area::SocialDevelopment->value, 'position' => 'Trabajadora Social',      'contract_type' => ContractType::Appointed->value,      'hire_date' => '2014-03-20', 'work_shift' => WorkShift::Morning->value,   'site' => Site::South->value, 'is_active' => true,  'notes' => null],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '41258963', 'first_name' => 'Fernando',  'last_name' => 'Lozano Rivas',         'birth_date' => '1993-10-11', 'gender' => Gender::Male->value,   'email' => 'f.lozano@municipio.gob.pe',   'phone' => '977654321', 'address' => 'Calle Libertad 852, Lima',      'marital_status' => MaritalStatus::Single->value,   'education_level' => EducationLevel::University->value,   'children_count' => 0, 'emergency_contact_name' => 'Elena Lozano',    'emergency_contact_phone' => '912345670', 'ruc' => null, 'pension_system' => PensionSystem::Afp->value,  'area' => Area::CivilRegistry->value,     'position' => 'Registrador Civil',       'contract_type' => ContractType::Cas->value,            'hire_date' => '2023-02-01', 'work_shift' => WorkShift::Morning->value,   'site' => Site::Main->value,  'is_active' => true,  'notes' => null],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '85236914', 'first_name' => 'Mariela',   'last_name' => 'Cárdenas Bautista',    'birth_date' => '1989-01-03', 'gender' => Gender::Female->value, 'email' => 'm.cardenas@municipio.gob.pe', 'phone' => '966543210', 'address' => 'Av. Colonial 963, Lima',        'marital_status' => MaritalStatus::Married->value,  'education_level' => EducationLevel::Technical->value,    'children_count' => 2, 'emergency_contact_name' => 'Hugo Cárdenas',   'emergency_contact_phone' => '923456780', 'ruc' => null, 'pension_system' => PensionSystem::Onp->value,  'area' => Area::Treasury->value,           'position' => 'Contadora',               'contract_type' => ContractType::Appointed->value,      'hire_date' => '2016-08-12', 'work_shift' => WorkShift::Morning->value,   'site' => Site::Main->value,  'is_active' => true,  'notes' => null],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '69874523', 'first_name' => 'Héctor',    'last_name' => 'Salas Cornejo',        'birth_date' => '1977-03-22', 'gender' => Gender::Male->value,   'email' => 'h.salas@municipio.gob.pe',    'phone' => '955432109', 'address' => 'Jr. Ancash 147, Lima',          'marital_status' => MaritalStatus::Married->value,  'education_level' => EducationLevel::Secondary->value,    'children_count' => 3, 'emergency_contact_name' => 'Teresa Salas',    'emergency_contact_phone' => '934567891', 'ruc' => null, 'pension_system' => PensionSystem::Onp->value,  'area' => Area::PublicCleaning->value,    'position' => 'Operario de Limpieza',    'contract_type' => ContractType::Hired->value,          'hire_date' => '2007-05-30', 'work_shift' => WorkShift::Afternoon->value, 'site' => Site::North->value, 'is_active' => true,  'notes' => null],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '52369874', 'first_name' => 'Verónica',  'last_name' => 'Arce Molina',          'birth_date' => '1991-07-16', 'gender' => Gender::Female->value, 'email' => 'v.arce@municipio.gob.pe',     'phone' => '944321098', 'address' => 'Urb. La Molina 258, Lima',      'marital_status' => MaritalStatus::Single->value,   'education_level' => EducationLevel::University->value,   'children_count' => 0, 'emergency_contact_name' => 'Raúl Arce',       'emergency_contact_phone' => '945678902', 'ruc' => null, 'pension_system' => PensionSystem::Afp->value,  'area' => Area::Health->value,             'position' => 'Enfermera',               'contract_type' => ContractType::Cas->value,            'hire_date' => '2020-11-05', 'work_shift' => WorkShift::Rotating->value, 'site' => Site::East->value,  'is_active' => true,  'notes' => null],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '78523614', 'first_name' => 'Ricardo',   'last_name' => 'Torres Espinoza',      'birth_date' => '1984-12-09', 'gender' => Gender::Male->value,   'email' => 'r.torres@municipio.gob.pe',   'phone' => '933210987', 'address' => 'Av. Argentina 369, Lima',       'marital_status' => MaritalStatus::Married->value,  'education_level' => EducationLevel::University->value,   'children_count' => 1, 'emergency_contact_name' => 'Isabel Torres',   'emergency_contact_phone' => '956789013', 'ruc' => '10785236141', 'pension_system' => PensionSystem::Afp->value, 'area' => Area::PublicWorks->value,       'position' => 'Arquitecto',              'contract_type' => ContractType::Appointed->value,      'hire_date' => '2011-09-18', 'work_shift' => WorkShift::Morning->value,   'site' => Site::Main->value,  'is_active' => true,  'notes' => null],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '96321478', 'first_name' => 'Isabel',    'last_name' => 'Rojas Pachari',        'birth_date' => '1994-04-01', 'gender' => Gender::Female->value, 'email' => 'i.rojas@municipio.gob.pe',    'phone' => '922109876', 'address' => 'Jr. Huancayo 741, Lima',        'marital_status' => MaritalStatus::Single->value,   'education_level' => EducationLevel::Technical->value,    'children_count' => 0, 'emergency_contact_name' => 'David Rojas',     'emergency_contact_phone' => '967890124', 'ruc' => null, 'pension_system' => PensionSystem::Afp->value,  'area' => Area::SocialDevelopment->value, 'position' => 'Promotora Social',        'contract_type' => ContractType::ServiceContract->value, 'hire_date' => '2022-06-15', 'work_shift' => WorkShift::Morning->value,   'site' => Site::West->value,  'is_active' => true,  'notes' => null],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '25478963', 'first_name' => 'Daniel',    'last_name' => 'Ccorimanya Quispe',    'birth_date' => '1980-09-27', 'gender' => Gender::Male->value,   'email' => 'd.ccorimanya@municipio.gob.pe','phone' => '911098765', 'address' => 'Calle Tacna 852, Lima',         'marital_status' => MaritalStatus::Married->value,  'education_level' => EducationLevel::Secondary->value,    'children_count' => 2, 'emergency_contact_name' => 'Nora Ccorimanya', 'emergency_contact_phone' => '978901235', 'ruc' => null, 'pension_system' => PensionSystem::Onp->value,  'area' => Area::CitizenSecurity->value,   'position' => 'Agente de Seguridad',     'contract_type' => ContractType::Hired->value,          'hire_date' => '2013-01-07', 'work_shift' => WorkShift::Night->value,     'site' => Site::South->value, 'is_active' => true,  'notes' => null],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '61478523', 'first_name' => 'Claudia',   'last_name' => 'Medina Alvarado',      'birth_date' => '1986-06-20', 'gender' => Gender::Female->value, 'email' => 'c.medina@municipio.gob.pe',   'phone' => '900987654', 'address' => 'Urb. San Borja 963, Lima',      'marital_status' => MaritalStatus::Divorced->value, 'education_level' => EducationLevel::University->value,   'children_count' => 1, 'emergency_contact_name' => 'Enrique Medina',  'emergency_contact_phone' => '989012346', 'ruc' => '10614785231', 'pension_system' => PensionSystem::Afp->value, 'area' => Area::EducationCulture->value,  'position' => 'Coordinadora Cultural',   'contract_type' => ContractType::Cas->value,            'hire_date' => '2017-04-22', 'work_shift' => WorkShift::Morning->value,   'site' => Site::Annex->value, 'is_active' => true,  'notes' => null],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '38741596', 'first_name' => 'Alberto',   'last_name' => 'Soto Fernández',       'birth_date' => '1976-11-14', 'gender' => Gender::Male->value,   'email' => 'a.soto@municipio.gob.pe',     'phone' => '999012345', 'address' => 'Av. Brasil 147, Lima',          'marital_status' => MaritalStatus::Married->value,  'education_level' => EducationLevel::Technical->value,    'children_count' => 3, 'emergency_contact_name' => 'Pilar Soto',      'emergency_contact_phone' => '990234567', 'ruc' => null, 'pension_system' => PensionSystem::Onp->value,  'area' => Area::Transportation->value,    'position' => 'Mecánico',                'contract_type' => ContractType::Hired->value,          'hire_date' => '2009-08-03', 'work_shift' => WorkShift::Morning->value,   'site' => Site::Main->value,  'is_active' => true,  'notes' => null],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '84521369', 'first_name' => 'Rosa',      'last_name' => 'Ccallo Hancco',        'birth_date' => '1996-02-14', 'gender' => Gender::Female->value, 'email' => 'r.ccallo@municipio.gob.pe',   'phone' => '988901234', 'address' => 'Jr. Cuzco 258, Lima',           'marital_status' => MaritalStatus::Single->value,   'education_level' => EducationLevel::University->value,   'children_count' => 0, 'emergency_contact_name' => 'Walter Ccallo',   'emergency_contact_phone' => '901345678', 'ruc' => null, 'pension_system' => PensionSystem::Afp->value,  'area' => Area::Administration->value,     'position' => 'Asistente Administrativa','contract_type' => ContractType::Intern->value,         'hire_date' => '2024-01-15', 'work_shift' => WorkShift::Morning->value,   'site' => Site::Main->value,  'is_active' => true,  'notes' => 'Practicante pre-profesional'],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '57896321', 'first_name' => 'Gustavo',   'last_name' => 'Villanueva Cruz',      'birth_date' => '1982-07-08', 'gender' => Gender::Male->value,   'email' => 'g.villanueva@municipio.gob.pe','phone' => '977890123', 'address' => 'Urb. Chorrillos 369, Lima',     'marital_status' => MaritalStatus::Married->value,  'education_level' => EducationLevel::University->value,   'children_count' => 2, 'emergency_contact_name' => 'Norma Villanueva', 'emergency_contact_phone' => '912456789', 'ruc' => '10578963211', 'pension_system' => PensionSystem::Afp->value, 'area' => Area::CivilRegistry->value,     'position' => 'Jefe de Registro Civil',  'contract_type' => ContractType::Appointed->value,      'hire_date' => '2013-05-27', 'work_shift' => WorkShift::Morning->value,   'site' => Site::Main->value,  'is_active' => true,  'notes' => null],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '32145896', 'first_name' => 'Gabriela',  'last_name' => 'Paredes Inca',         'birth_date' => '1997-09-05', 'gender' => Female->value, 'email' => 'g.paredes@municipio.gob.pe',  'phone' => '966789012', 'address' => 'Av. La Marina 741, Lima',       'marital_status' => MaritalStatus::Single->value,   'education_level' => EducationLevel::University->value,   'children_count' => 0, 'emergency_contact_name' => 'Juan Paredes',    'emergency_contact_phone' => '923567890', 'ruc' => null, 'pension_system' => PensionSystem::Afp->value,  'area' => Area::Environment->value,       'position' => 'Bióloga',                 'contract_type' => ContractType::Cas->value,            'hire_date' => '2023-08-01', 'work_shift' => WorkShift::Morning->value,   'site' => Site::East->value,  'is_active' => true,  'notes' => null],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '79632145', 'first_name' => 'Marcos',    'last_name' => 'Huanca Quispe',        'birth_date' => '1973-04-19', 'gender' => Gender::Male->value,   'email' => 'm.huanca@municipio.gob.pe',   'phone' => '955678901', 'address' => 'Jr. Puno 852, Lima',            'marital_status' => MaritalStatus::Married->value,  'education_level' => EducationLevel::Secondary->value,    'children_count' => 4, 'emergency_contact_name' => 'Elvira Huanca',   'emergency_contact_phone' => '934678901', 'ruc' => null, 'pension_system' => PensionSystem::Onp->value,  'area' => Area::PublicCleaning->value,    'position' => 'Operario de Parques',     'contract_type' => ContractType::Hired->value,          'hire_date' => '2005-10-10', 'work_shift' => WorkShift::Morning->value,   'site' => Site::West->value,  'is_active' => true,  'notes' => null],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '46523897', 'first_name' => 'Diana',     'last_name' => 'Palomino Tapia',       'birth_date' => '1990-12-31', 'gender' => Gender::Female->value, 'email' => 'd.palomino@municipio.gob.pe', 'phone' => '944567890', 'address' => 'Calle Ayacucho 963, Lima',      'marital_status' => MaritalStatus::Married->value,  'education_level' => EducationLevel::University->value,   'children_count' => 1, 'emergency_contact_name' => 'José Palomino',   'emergency_contact_phone' => '945789012', 'ruc' => null, 'pension_system' => PensionSystem::Afp->value,  'area' => Area::Health->value,             'position' => 'Psicóloga',               'contract_type' => ContractType::Cas->value,            'hire_date' => '2019-03-18', 'work_shift' => WorkShift::Morning->value,   'site' => Site::North->value, 'is_active' => true,  'notes' => null],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '93654128', 'first_name' => 'Andrés',    'last_name' => 'Morales Benavides',    'birth_date' => '1979-08-22', 'gender' => Gender::Male->value,   'email' => 'a.morales@municipio.gob.pe',  'phone' => '933456789', 'address' => 'Urb. Miraflores 147, Lima',     'marital_status' => MaritalStatus::Married->value,  'education_level' => EducationLevel::University->value,   'children_count' => 2, 'emergency_contact_name' => 'Carla Morales',   'emergency_contact_phone' => '956890123', 'ruc' => '10936541281', 'pension_system' => PensionSystem::Afp->value, 'area' => Area::PublicWorks->value,       'position' => 'Supervisor de Obras',     'contract_type' => ContractType::Appointed->value,      'hire_date' => '2010-12-01', 'work_shift' => WorkShift::Morning->value,   'site' => Site::Main->value,  'is_active' => true,  'notes' => null],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '15236984', 'first_name' => 'Estela',    'last_name' => 'Lazo Aguilar',         'birth_date' => '1985-05-07', 'gender' => Gender::Female->value, 'email' => 'e.lazo@municipio.gob.pe',     'phone' => '922345678', 'address' => 'Jr. Arequipa 258, Lima',        'marital_status' => MaritalStatus::Single->value,   'education_level' => EducationLevel::Technical->value,    'children_count' => 0, 'emergency_contact_name' => 'César Lazo',      'emergency_contact_phone' => '967901234', 'ruc' => null, 'pension_system' => PensionSystem::Onp->value,  'area' => Area::Administration->value,     'position' => 'Secretaria',              'contract_type' => ContractType::Cas->value,            'hire_date' => '2021-04-12', 'work_shift' => WorkShift::Morning->value,   'site' => Site::Annex->value, 'is_active' => true,  'notes' => null],
            // Inactivos
            ['document_type' => DocumentType::Dni->value,        'document_number' => '68423159', 'first_name' => 'Luis',      'last_name' => 'Cano Aguirre',         'birth_date' => '1968-03-15', 'gender' => Gender::Male->value,   'email' => 'l.cano@ex.municipio.gob.pe',  'phone' => '911234567', 'address' => 'Av. Javier Prado 369, Lima',    'marital_status' => MaritalStatus::Married->value,  'education_level' => EducationLevel::University->value,   'children_count' => 3, 'emergency_contact_name' => 'Diana Cano',      'emergency_contact_phone' => '978012345', 'ruc' => '10684231591', 'pension_system' => PensionSystem::Onp->value, 'area' => Area::Administration->value,     'position' => 'Ex Director',             'contract_type' => ContractType::Appointed->value,      'hire_date' => '2000-01-01', 'work_shift' => WorkShift::Morning->value,   'site' => Site::Main->value,  'is_active' => false, 'notes' => 'Jubilado'],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '27896541', 'first_name' => 'María',     'last_name' => 'Quispe Mamani',        'birth_date' => '1965-09-10', 'gender' => Gender::Female->value, 'email' => 'm.quispe.ex@municipio.gob.pe', 'phone' => '900123456', 'address' => 'Jr. Lima 741, Lima',            'marital_status' => MaritalStatus::Widowed->value,  'education_level' => EducationLevel::Primary->value,      'children_count' => 5, 'emergency_contact_name' => 'Félix Quispe',    'emergency_contact_phone' => '989123456', 'ruc' => null, 'pension_system' => PensionSystem::Onp->value,  'area' => Area::PublicCleaning->value,    'position' => 'Ex Operaria',             'contract_type' => ContractType::Hired->value,          'hire_date' => '2002-05-15', 'work_shift' => WorkShift::Morning->value,   'site' => Site::South->value, 'is_active' => false, 'notes' => 'Cese definitivo'],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '53698741', 'first_name' => 'Pablo',     'last_name' => 'Yupanqui Caso',        'birth_date' => '1970-12-05', 'gender' => Gender::Male->value,   'email' => 'p.yupanqui.ex@municipio.gob.pe','phone' => '999234567', 'address' => 'Calle Ica 852, Lima',           'marital_status' => MaritalStatus::Divorced->value, 'education_level' => EducationLevel::Secondary->value,    'children_count' => 1, 'emergency_contact_name' => 'Nelly Yupanqui',  'emergency_contact_phone' => '990345678', 'ruc' => null, 'pension_system' => PensionSystem::Onp->value,  'area' => Area::Transportation->value,    'position' => 'Ex Conductor',            'contract_type' => ContractType::Hired->value,          'hire_date' => '2003-08-20', 'work_shift' => WorkShift::Afternoon->value, 'site' => Site::North->value, 'is_active' => false, 'notes' => 'Renuncia voluntaria'],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '81459632', 'first_name' => 'Angélica',  'last_name' => 'Ñaupa Tito',           'birth_date' => '1972-06-18', 'gender' => Gender::Female->value, 'email' => 'a.naupa.ex@municipio.gob.pe', 'phone' => '988345678', 'address' => 'Urb. San Juan 963, Lima',       'marital_status' => MaritalStatus::Married->value,  'education_level' => EducationLevel::Technical->value,    'children_count' => 2, 'emergency_contact_name' => 'Hugo Ñaupa',      'emergency_contact_phone' => '901456789', 'ruc' => null, 'pension_system' => PensionSystem::Onp->value,  'area' => Area::Health->value,             'position' => 'Ex Técnica en Salud',     'contract_type' => ContractType::Cas->value,            'hire_date' => '2005-03-10', 'work_shift' => WorkShift::Rotating->value, 'site' => Site::East->value,  'is_active' => false, 'notes' => 'Término de contrato'],
            ['document_type' => DocumentType::Dni->value,        'document_number' => '64785239', 'first_name' => 'Víctor',    'last_name' => 'Aponte Delgado',       'birth_date' => '1967-01-24', 'gender' => Gender::Male->value,   'email' => 'v.aponte.ex@municipio.gob.pe', 'phone' => '977456789', 'address' => 'Av. Grau 147, Lima',            'marital_status' => MaritalStatus::Married->value,  'education_level' => EducationLevel::University->value,   'children_count' => 4, 'emergency_contact_name' => 'Lucía Aponte',    'emergency_contact_phone' => '912567890', 'ruc' => '10647852391', 'pension_system' => PensionSystem::Onp->value, 'area' => Area::PublicWorks->value,       'position' => 'Ex Ingeniero',            'contract_type' => ContractType::Appointed->value,      'hire_date' => '1998-07-01', 'work_shift' => WorkShift::Morning->value,   'site' => Site::Main->value,  'is_active' => false, 'notes' => 'Jubilado por años de servicio'],
        ];

        // Se usa Person::create() para que se disparen eventos y podamos usar Spatie MediaLibrary
        // Asignamos una foto de randomuser.me basada en el género.
        foreach ($persons as $personData) {
            $person = Person::create($personData);

            try {
                // Seleccionar URL según el género
                $gender = $person->gender->value === Gender::Male->value ? 'men' : 'women';
                $randomNumber = rand(1, 99); // API de randomuser tiene fotos del 1 al 99
                
                $photoUrl = "https://randomuser.me/api/portraits/{$gender}/{$randomNumber}.jpg";

                $person->addMediaFromUrl($photoUrl)->toMediaCollection('avatar');
                
                $this->command?->info("Foto asignada para {$person->first_name} {$person->last_name}");
            } catch (\Exception $e) {
                // Si falla (ej. sin internet), continuamos sin asignar la foto
                $this->command?->error("No se pudo descargar la foto para {$person->first_name}: " . $e->getMessage());
            }
        }

        $this->command?->info('Módulo Personas: 30 registros creados (con fotos de randomuser.me).');
    }
}
